# Generated by Django 5.2.12 on 2026-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentsession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="student",
            name="rating",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
